"use client"

import './globals.css'

import { GoogleOAuthProvider } from '@react-oauth/google'
import { Inter } from 'next/font/google'
import Provider from '@/components/Provider'

const client_id = process.env.CLIENT_ID as string
if (!client_id){
  throw new Error('No client id')
}


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Provider> */}
        <GoogleOAuthProvider clientId = {client_id}>
        <main>{children}</main>
        </GoogleOAuthProvider>
        {/* </Provider> */}
        </body>
        
    </html>
  )
}
