export const EN_US = {
	sendDataButton: "Send Data",
	dateRangePrompt: "Choose the date range to fetch calendar data.",
	fetchingEvents: "Fetching events...",
	eventsRetrieved: "Events retrieved",
	unknownFetchError: "Unknown error during fetching.",
	noFetchData: "No data",
	unknownErrorOccurred: "An error occurred.",
	fetchDataButtonText: "Fetch Data",
	createDateEvent: "Create date event",
	createDateTimeEvent: "Create datetime event",
	deleteSelectedEvents: "Delete selected events",
	from: "From",
	to: "To",
	restoreDeletedItems: "Restore Deleted Items",
	noChangedData: "No changed data to send.",
	requestsFailed: "Something went wrong with the request(s).",
	updatedEvents: "Successfully updated events.",
} as const;
